### ISSUE TITLE
[FEATURE] Add auto dependency upgrades for SDK

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-sdk-java#185]
### Is your feature request related to a problem?
Add github dependabot support which raises PRs when security issues are found within code. 

### What solution would you like?
Write up `dependabot.yml` and configure it for the repo[1].

[1] https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

**Comment by dbwiddis** [comment]
I recently replaced Dependabot on my repo with [Renovate](https://www.mend.io/free-developer-tools/renovate/).  I consider it much better of a product.  Some advantages:
 - If you want it to act just like Dependabot you can, but you can even customize time of day of the PRs, or just let them come whenever detected.
 - You can group/batch version bumps together. I have done this to batch my build plugins (to get a single PR instead of 3 for ones that release together, for example) to reduce the PR noise.
 - It creates a "Dashboard" issue that shows you any pending bumps or ones you've intentionally suppressed.  See example [here](https://github.com/oshi/oshi/issues/2160).
 - It has the ability to auto-merge its own PRs, which I've enabled for minor and patch versions of build plugins.  We probably don't want that feature here, but it's available :) 

Unless there's a reason we are tied to the same system as OpenSearch, I'd consider it.

**Comment by dbwiddis** [comment]
Some bloggers like Renovate:
 - [Software Dependency Management: From Dependabot to Renovate](https://meabed.medium.com/software-dependency-management-from-dependabot-to-renovate-5b4e749b5b1c)
 - [Automate Dependency Updates With Renovate, Not With Dependabot](https://javascript.plainenglish.io/automate-dependency-updates-by-renovate-not-by-dependabot-6efddd549a3e)

Other reasons Renovate is awesome (and no I'm not a paid shill):
 - The company behind it (Mend) is a rebrand from WhiteSource which we already use/trust in our CI
 - Dependabot works great for Github.  Because it's developed by GitHub.  As an independent product, Renovate supports many more platforms than GitHub, which may or may not be relevant in our future if we have more Docker integration, etc.

**Comment by saratvemulapalli** [comment]
Thanks @dbwiddis. I didnt know Mend Renovate is really better. I really like that. 
I am happy as long as dependencies are being upgraded : )

**Comment by dbwiddis** [comment]
This needs to be initially setup by an owner of `opensearch-project`. How do we request that?
