### ISSUE TITLE
[Feature/extensions] Add getNamedWriteableRegistry() API for extensions

### ISSUE THREAD

**Issue by ryanbogan** [opensearch-project/opensearch-sdk-java#291]
The old model for the getNamedWriteableRegistry() was recently removed, due to concerns here: https://github.com/opensearch-project/OpenSearch/pull/5518#discussion_r1049668323.  A new model must be created, which should be similar to the implementation of getNamedXContent().

**Comment by dbwiddis** [comment]
@ryanbogan this looks like it's already done here:
https://github.com/opensearch-project/opensearch-sdk-java/blob/1261c46e3055dc98e5d089b65deca439e343050b/src/main/java/org/opensearch/sdk/NettyTransport.java#L69-L76

Is there still work to be done on this?

**Comment by dbwiddis** [comment]
Ah, I see we create it but we don't integrate the portion of it that comes from an extension itself.  SO that bit needs to be added.

**Comment by petiveriaalliacea** [comment]
Hello! I want to take this issue. Where can I find nessesary classes and methods? And in what part here is missing and should be implemented?

**Comment by dbwiddis** [comment]
Hi, @petiveriaalliacea!  Thanks for stepping up.  

Take a look at how the `getNamedXContent()` extension point is currently implemented with the `ExtensionsRunner` constructor, `ExtensionsInitRequestHandler`, and `SDKNamedXContentRegistry`.   

You will basically be doing the exact same thing with the `getNamedWriteables()` extension point:
1. Create a new `SDKNamedWriteableRegistry` class similar to the `SDKNamedXContentRegistry`
2. Internally in that class, instead of the OpenSearch module static NamedXContent, use the static NamedWriteable implementations from here https://github.com/opensearch-project/OpenSearch/blob/f332977666f9839b5bfa507f9ffe77e8134d2481/server/src/main/java/org/opensearch/node/Node.java#L599 (You'll have to follow each method call to see what it actually loads)
3. Add the default method to the `Extension` interface
4. Create a private field in the `ExtensionsRunner` for the `SDKNamedWriteableRegistry`
5. Create a getter for the field you just created
6. During initialization, instantiate this registry prior to injecting components
7. Add the registry to the components injected in Guice
8. In the `ExtensionInitRequestHandler` update the registry once you have updated settings from OpenSearch

I think that's mostly it, let us know if you have any questions.

**Comment by dbwiddis** [comment]
Actually, @petiveriaalliacea it's slightly more (and less) complicated than the above.  
 - I realized reading [this comment](https://github.com/opensearch-project/opensearch-sdk-java/issues/291#issuecomment-1377910013) that we already have a partial implementation in the `NettyTransport` class.  So that class needs a copy of this registry.
 - I looked into the registration in `Node.java` linked in the comment above and none of it depends on updated settings, so it's okay to initialize this once.   

So updated steps:
You will basically be doing the exact same thing with the `getNamedWriteables()` extension point:
1. Create a new `SDKNamedWriteableRegistry` class similar to the `SDKNamedXContentRegistry`, except you won't need an update method
2. Internally in that class, instead of the OpenSearch module static NamedXContent, use the NamedWriteable implementations from here https://github.com/opensearch-project/OpenSearch/blob/f332977666f9839b5bfa507f9ffe77e8134d2481/server/src/main/java/org/opensearch/node/Node.java#L599 .  You can call the static method on one, and instantiate the class to call the getter on the others.  This was done in the `NettyTransport` class but you'll want to move it into that new class.
3. Delete the creation of this registry from the `NettyTransport` class. Instead, add the registry as a parameter to the `getNetty4Transport` method.
4. Add the default method to the `Extension` interface
5. Create a private field in the `ExtensionsRunner` for the `SDKNamedWriteableRegistry` with a getter
6. During initialization, instantiate this registry prior to injecting components
7. Add the registry to the components injected in Guice (just use the getter from the `SDK` registry to inject the actual `NamedWriteableRegistry`)
8. During transport initialization, pass the registry to the `NettyTransport` method you changed in step 3.

**Comment by dbwiddis** [comment]
Done in #553
