### ISSUE TITLE
Migrate Stop Detector job to SDK using SDKRestClient

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#384]
### Is your feature request related to a problem?
 
Part of https://github.com/opensearch-project/OpenSearch/issues/5224
 
### What solution would you like?
 
Migrate the Stop Detector job Rest API to Extensions SDK using SDKRestClient.
 
Use the implementation of #353 as a reference.  Add new issues for any steps you skip.
 
Implement the following API endpoints:
 - [ ] `POST _plugins/_anomaly_detection/detectors/<detectorId>/_stop`

**Comment by joshpalis** [comment]
### Completed Tasks:

- [ ] Modify `StopDetectorTransportAction` to extend directly from `TransportAction` and register within `getActions`
- [ ] Replace client/cluster service with corresponding SDK classes, refactor OpenSearch action invocations with corresponding `OpenSearchAsyncClient` methods (if any) and register required created components to inject into `DeleteModelTransportAction`
   - [ ] SearchFeatureDao
   - [ ] NodeStateManager
   - [ ] FeatureManager
   - [ ] CheckpointDao
   - [ ] CheckpointWriteWorker
   - [ ] EntityColdStarter
   - [ ] ModelManager
- [ ] Fix affected test classes

### Remaining Tasks:

- [ ] Modify `DeleteModelTransportAction` to extend directly from `TransportAction` rather than from `TransportNodeAction` and register within `getActions`. This is invoked by `StopDetectorTransportAction`

**Comment by minalsha** [comment]
@joshpalis  I see PR for stop detector:https://github.com/opensearch-project/anomaly-detection/pull/845 merged. Can we close this issue?
