### ISSUE TITLE
[FEATURE] Track User Access/Roles when creating a detector

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#63]
### Is your feature request related to a problem?
In the current AD Plugin model, the `User` which created a detector is stored with the detector, along with their roles.  If the detector is updated later, the access/roles of the original user are retained.  
```java
User detectorUser = currentDetector == null ? user : currentDetector.getUser();
```

In our current "without security" implementation this is not an issue; we will store the `null` (super-admin) user when creating the detector.  However, looking to the future, we need to replace the current "User"-based roles with RBAC-determined roles integrated with the security access model.

### What solution would you like?

When the new security features are developed, there will be a need to "preserve the roles of the initial creator".  The above line of code identifying the "detectorUser" will need to be removed and the User field of the `IndexAnomalyDetectorActionHandler` will need to integrate with the create detector code in a way that doesn't replace the roles.

### What alternatives have you considered?
Keeping the roles in the existing UserIdentity object rather than only passing access tokens and looking up the roles internally to the OpenSearch security features.  This would be a security flaw; Identity Tokens and Access Tokens are separate things and we should assume any token held by an extension can be compromised/edited.

### Do you have any additional context?
See background in this issue: https://github.com/opensearch-project/anomaly-detection/issues/124

**Comment by dbwiddis** [comment]
@peternied FYI and action as part of security feature development.

**Comment by DarshitChanpura** [comment]
SDK/Extensions should not track user/roles access. Each extension should use checkPermissions API to check for user/role access for the requested action.

For AD plugin's Detector permissions, there should be a call to the checkPermissions API before a detector is created, accessed, modified, or deleted.

**Comment by dbwiddis** [comment]
> For AD plugin's Detector permissions, there should be a call to the checkPermissions API before a detector is created, accessed, modified, or deleted.

Can you give a code example?   What credentials are needed to check permissions, e.g., if I'm a rogue extension and get a RestRequest with the principal identity token, does this unlock me doing anything I want with this login information?

**Comment by DarshitChanpura** [comment]
AFAIK, we don't have a concrete implementation yet to give you a code example. However, the API was implemented as part of https://github.com/opensearch-project/OpenSearch/pull/4516 and the class AuthorizationRequest would give a basic idea of what params are needed to make authorization request.

> if I'm a rogue extension and get a RestRequest with the principal identity token, does this unlock me doing anything I want with this login information?

Although the token is extension specific, this may be a potential risk depending on what actions can this extension do. Coming to think about it, how should we ensure that all extensions implement a valid call to checkPermissions API and not bypass it?
@peternied @cwperks Thoughts?

**Comment by cwperks** [comment]
@DarshitChanpura Extensions will have permissions themselves so administrators can constrain what the extension itself can do. AD will need to be able to persist objects it creates like detectors and results and an administrator may also want to constrain the set of indices that the extension can read in addition to individual user permissions.

@dbwiddis My current understanding is that rest API actions hit core and then core relays the request to the extension if it matches a registered extension API. There will be a layer of security to evaluate privileges on the request in core before its relayed to the extension, buts its not fully figured out how this will happen. Input is welcome :).

For an action like create a detector, it may be similar to the way it is today where a user needs to resolve to a list of permissions that includes `cluster:admin/opendistro/ad/detectors/write` or however we agree upon naming the permissionId/actionName. One of the challenges I am seeing with moving some of the authorization into core is how we can provide frameworks for extensions developers to provide security on resources. If extensions developers are getting a volatile token that identifies the subject, then they have no way of correlating who created a resource once the subject gets a new token. Currently AD is doing its own implementation of authorization for modifying detectors where a user is permitted to modify another user's detector if they share a backend role. 

One of the challenges for extensions security is to what extent can we perform authorization in core and if extensions developers want to provide additional security features in the extension then how can they do so? Since creating objects may be a common use-case in extensions, I think we should develop some policies around how to protect generic objects and granting permission to another user/group to modify the object. Or granting permission to a user on a group of objects.

We need a mechanism for registering permissions/actionNames in an extension and a way to assign the privileges to users (subjects in our current `feature/identity` lingo). Should we provide a mechanism for extensions developers to explicitly ask if a subject has permissions that incurs an additional round-trip to evaluate?

pseudo-code:

```
// Evaluated on current subject
if (canPerform(<permission_id_or_action_name>, {"param1": "value1"}) {
    ...
}
```

I haven't thought about this in too much detail yet, but actions are performed by subjects (not by extensions). If an extension developer gets a token then their bounds are the intersection of the extension permission and subject permissions.

**Comment by dbwiddis** [comment]
> There will be a layer of security to evaluate privileges on the request in core before its relayed to the extension, buts its not fully figured out how this will happen. Input is welcome :).

For the RestRequest forwarding, there is a small time-boxed window during which this interchange happens, currently hardcoded to 5 seconds but we might choose to make that configurable.  I would think that any token information sent to the extension would have that same expiration, i.e., if the extension doesn't respond in the permitted time frame, it's no longer valid (or it is invalidated instantly upon receiving the response).

>  If extensions developers are getting a volatile token that identifies the subject, then they have no way of correlating who created a resource once the subject gets a new token. 

We probably need both the identity token (which does not confer access) AND the volatile access token.

**Comment by minalsha** [comment]
Security team: @peternied  and team is handling this.
