### ISSUE TITLE
[FEATURE] Publish artifacts to Maven

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-sdk-java#75]
### Is your feature request related to a problem?
Publish SDK artifacts to Maven repositories for extension authors to consume

**Comment by dbwiddis** [comment]
What benefit does publishing our under-development sdk work provide to extension authors?  We still haven't decided on a name!

I'm completely on board with publishing an alpha version once we've got something that the community can build on but I don't think we're there yet.

**Comment by dblock** [comment]
Generally publishing -SNAPSHOTs is good practice, especially in early stages. Simplifies development of extensions by removing the need to build this repo and publishing to maven local. Automates early.

Because we use aws.oss.sonatype I wouldn't be concerned with naming too much, but would still do #56 first.

**Comment by dbwiddis** [comment]
As soon as we are at the point where an extension needs to consume content from the SDK, this will be a requirement, and we are probably nearing that point with the AD work.  So yes, let's do the name change and then start publishing.

**Comment by saratvemulapalli** [comment]
Issue on OpenSearch build: https://github.com/opensearch-project/opensearch-build/issues/3011
