### ISSUE TITLE
Add create component extension point support for AD

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-sdk-java#78]
With AD detectors, lets add support for create components and integrate with the work already done with https://github.com/opensearch-project/opensearch-sdk/pull/44

**Comment by joshpalis** [comment]
`createComponents` allows plugins to return a collection of objects to OpenSearch. PluginService iterates through all plugins and passes several services and registries, ie `clusterService`, `environment`, `client`, `NamedXContentRegistry` to help these plugins to configure and generate their components. These objects are then consolidated into a list, which is then bound to a Guice module during node initialization and then further used for dependency injection. In the case of extensibility, since these extensions are running an independent processes, we must add support to transport the necessary information from the services required to successfully create these components. In the case of Anomaly Detection, in order to support creating a detector, the required components are `AnomalyDetectionIndices`, `SearchFeatureDao`, and `ADTaskManager`.  

These components require several services from OpenSearch, and currently there is added support for the following : 

- Client : replaced by [SDKClient](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/src/main/java/org/opensearch/sdk/SDKClient.java)

Some of the required services from OpenSearch are not necessary to add support for as they are not required for creating a detector : 

- NamedXContentRegistry : replaced with an empty collection

These objects require transport APIs to be created in order to access :

- ClusterService
- Settings

`ClusterService` is used by Anomaly Detection to access the `ClusterSettings` in order to add custom settings update consumers. These custom consumers are added within the object constructors of each component, so it is necessary to enable extensions to perform these actions as part of component creation. 

For example : 

- For `ADTaskManager` : https://github.com/joshpalis/anomaly-detection/blob/572fd8d4f08691326d92535f88f7d5f06ea4ea63/src/main/java/org/opensearch/ad/task/ADTaskManager.java#L233 
- For `AnomalyDetectionIndices` : https://github.com/joshpalis/anomaly-detection/blob/572fd8d4f08691326d92535f88f7d5f06ea4ea63/src/main/java/org/opensearch/ad/indices/AnomalyDetectionIndices.java#L201
- For `SearchFeatureDao` : https://github.com/joshpalis/anomaly-detection/blob/572fd8d4f08691326d92535f88f7d5f06ea4ea63/src/main/java/org/opensearch/ad/feature/SearchFeatureDao.java#L117

To add support for extensions to add custom settings update consumers during create components : 

- [ ] Create a Transport Request from extensions to OpenSearch to add custom settings update consumers
- [ ] Use `ExtensionsOrchestrator`'s clusterService, which is initialized [here](https://github.com/opensearch-project/OpenSearch/blob/feature/extensions/server/src/main/java/org/opensearch/extensions/ExtensionsOrchestrator.java#L146) and invoke `getClusterSettings.addSettingsUpdateConsumer` with the transported parameters
- [ ] Send an acknowledgement to the extension upon successfully adding in the consumer

`Settings` come from the node environment, which is created [here](https://github.com/opensearch-project/OpenSearch/blob/feature/extensions/server/src/main/java/org/opensearch/node/Node.java#L440) . To add support for extensions : 

- [X] Pass in environment settings from `Node.java` to `ExtensionsOrchestrator` during node initialization
- [X] Create a Transport Request from extensions to OpenSearch for environment settings

Once these transport APIs are created, integrating the opensearch-sdk with Anomaly Detection would allow us call these transport APIs to retrieve the necessary information to generate the necessary components.
